import img1 from '../image/1/1.png';
import img2 from '../image/1/2.png';
import img3 from '../image/1/3.png';

const data = [
    {
      id: 1,
      name: "Viaje al sur de España 6 días desde Madrid",
      stock: 20,
      price: 720,
      descrption: "Disfrute de 6 días para visitar una de las regiones con más riqueza cultural de España. Impresionante oferta de tour por Andalucía recorriendo las joyas del sur de la Península Ibérica: Granada, Córdoba, Sevilla. Una experiencia única para conocer los encantos de Andalucía. Circuito de 6 días para hacer un precioso Tour por el Sur de España, descubra Andalucía tanto para individuales como para circuitos en grupo. Una buena oferta a un buen precio, donde los vuelos no están incluidos.",
      includ: "Visitas en Sevilla, Córdoba Granada (Alhambra y Jardines Generalife) y Toledo / Asistencia de guía acompañante durante el circuito / Transporte en autobús moderno con aire acondicionado / Alojamiento en hoteles de clase superior 4* / Desayuno diario / 6 comidas incluidas / Seguro turístico.",
      img:img1,
      category: "ESPAÑA",
    },
    {
      id: 2,
      name: "Circuito – tour por la costa cantabrica desde Barcelona",
      stock: 20,
      price: 140,
      descrption: "Tour por el Norte de España con salida desde Barcelona (también desde Madrid), para descubrir el norte de la Península Ibérica que encierra una gran diversidad paisajística: acantilados abruptos, pequeñas islas, estuarios profundos, espaciosas bahías y preciosas playas, pero también un importante conjunto de monumentos y bienes culturales. Viajes al Norte de España saliendo desde Barcelona.",
      includ:"Guía acompañante durante el circuito / Transporte en autobus moderno con aire acondicionado / Alojamiento en hoteles de clase superior 4* / Desayuno buffet diario / 3 cenas / Seguro turístico.",
      img:img2,
      category: "ESPAÑA",
    },
    {
      id: 3,
      name: "Circuito por el norte de España y Portugal",
      stock: 20,
      price: 1440,
      descrption:"Viaje por el Norte de la Península Ibérica a lo largo de la Costa Cantábrica hasta el Atlántico, descubriendo paisajes de gran belleza. Tour por el Norte de España y Portugal con salidas desde Madrid. Viajamos desde el País Vasco, pasando por Cantabria, Asturias y Galicia con sus magníficas Rías Baixas hasta Portugal, pasando por Viana do Castelo, Braga, Oporto, Coimbra, Fátima y Lisboa.",
      includ:"Visita guiada de Santiago, Oporto y Lisboa / Guía acompañante durante el circuito / Transporte en autobús moderno con aire acondicionado / Alojamiento en hoteles de categoría superior 4* / Desayuno diario y 7 cenas / Visita a una bodega con degustación de vino / Tasas Municipales en Oporto y Lisboa / Seguro turístico.",
      img:img3,
      category: "ESPAÑA",
    },
    {
      id: 4,
      name: "Gran viaje de Marruecos desde Madrid",
      stock: 20,
      price: 960,
      descrption:"Paquete turístico a Marruecos con salida desde Madrid, España. Gran Tour de Marruecos desde España, para conocer las Ciudades Imperiales: Fez, Meknés, Marrakech, Rabat, Casablanca… Historia, cultura, monumentos majestuosos y una gastronomía que sorprende. Un itinerario muy completo por los lugares imprescindibles de Marruecos con guía en español.",
      includ:"Visitas indicadas en el itinerario / Asistencia de guía acompañante durante el circuito / Transporte en autobus moderno con aire acondicionado / Alojamiento en clase seleccionada / Media Pensión (desayuno y cena) en Marruecos / Tickets Fast Ferry ida y vuelta / Tickets AVE Madrid – Málaga – Madrid / Seguro de viaje.",
      img:img1,
      category: "ESPAÑA",
    },
    {
      id: 5,
      name: "Glamour francés 8 días desde la Costa Azul",
      stock: 20,
      price: 990,
      descrption:"Tours a Francia con salida desde la Costa Azul. Acompañados por expertos guías de habla hispana conoceremos los lugares más emblemáticos de la Riviera Francesa (Niza, Mónaco o Saint Tropez). Continuamos a lo largo de la Costa Mediterránea para conocer Marsella, la segunda ciudad de Francia. Seguimos hacía el interior hasta París vía Lyon, la Antigua capital de la Galia durante el Imperio Romano.",
      includ:"Traslado de llegada (aeropuerto – hotel) en Costa Azul / Recorrido en autocar moderno con guía de habla hispana / Visita panorámica en París / Excursión al Palacio de Versalles desde París / Traslado al Barrio de Montmartre en París / Subida en funicular a la Basílica de Lyon / Entradas a Carrieres de Lumiere en Beaux, Castillo medieval de La Rochepot y Abadía de Fontenay / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / Seguro turístico.",
      img:img2,
      category: "EUROPA",
    },
    {
      id: 6,
      name: "Paquete a Roma, Florencia & Venecia desde Roma",
      stock: 20,
      price: 940,
      descrption:"Viaje a Italia para visitar Roma, Florencia y Venecia. Acompañados de guías de habla hispana visitarán lo mejor de Roma, visita panorámica de Roma de Noche, los Museos Vaticanos, Capilla Sixtina y Basílica de San Pedro con entradas incluidas, seguimos a Florencia, conocida como la Ciudad del Arte, Asís, centro espiritual y de paz, Siena con sus esplendidos palacios, Bolonia, capital de la región de Emilia Romaña y Padua, conocida por la figura de San Antonio, y también Venecia, uno de los lugares más fascinantes del mundo, con sus canales surcados por góndolas y con sus característicos puentes. Gran tour de Italia con guías en español.",
      includ:"Traslado de llegada y salida en Roma (Aeropuerto – Hotel – Aeropuerto) / Transporte en autobús moderno con aire acondicionado / Asistencia de guía acompañante / Visita con guía local en Roma, Florencia y Venecia / Entrada a los Museos Vaticanos, Capilla Sixtina y Basílica de San Pedro en Roma y Basílica de San Marcos en Venecia / 7 noches de alojamiento en hoteles de clase superior / Desayuno tipo buffet / 2 almuerzos y 2 cenas / Seguro turístico.",
      img:img3,
      category: "EUROPA",
    },
    {
      id: 7,
      name: "Grecia peninsular 7 días desde Atenas",
      stock: 20,
      price: 940,
      descrption:"Viaje de 7 días por la región continental de Grecia con guías en español. Salimos hacia la región de Tesalia en el norte de Grecia, para visitar los Monasterios de Meteora. El siguiente destino es Delfos, sede del oráculo más importante de la antigüedad. Continuamos con la visita de la mítica Atenas, emblema universal del mundo clásico. Continuamos dirección sur por el Peloponeso para conocer Corinto, Micenas, luego Olimpia, cuna de los Juegos Olímpicos y el espléndido Teatro de Epidauro.",
      includ:"Traslados de llegada (aeropuerto – hotel) en Atenas / Transporte en autocar moderno con guía de habla hispana / Visita panorámica en Atenas y Olimpia / Entradas al Monasterio de Meteora, Recinto arqueológico de Delfos, Fortaleza Acrocorinto, Micenas, Recinto arqueológico de Olimpia, Castillo de Patras, Teatro griego de Epidauro / Trayectos en barco Galatas – Poros – Egina – Atenas / Traslado al Barrio de Plaka en Atenas / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / 3 cenas indicadas en el itinerario / Seguro turístico.",
      img:img1,
      category: "EUROPA",
    },
    {
      id: 8,
      name: "Capitales del imperio 8 días desde Praga",
      stock: 20,
      price: 935,
      descrption:"Paquete a Europa Central para conocer tres de las ciudades más impresionantes de Europa, cargadas de historia y salpicadas de majestuosos monumentos arquitectónicos. Visitamos Praga, con sus coloridos edificios barrocos e imponentes iglesias góticas. Seguimos hasta Hungría para visitar la mágica Budapest, a orillas del Danubio, una de las ciudades más visitadas de Europa. Continuamos a Austria para conocer Viena, una de las más antiguas capitales de Europa, pero también Innsbruck, capital de Tirol asentada en las faldas de los majestuosos Alpes.",
      includ:"Traslado de llegada (aeropuerto – hotel) en Praga / Transporte en autocar moderno con guía de habla hispana / Visita panorámica en Praga, Budapest, Viena e Innsbruck / Traslado al centro histórico de Praga, zona peatonal de Budapest y a la Plaza del Ayuntamiento en Viena / Entradas al Museo de la Cerveza en Pilsen / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / Seguro turístico.",
      img:img2,
      category: "EUROPA",
    },
    {
      id: 9,
      name: "Suiza espectacular 5 días desde Zúrich",
      stock: 20,
      price: 885,
      descrption:"Viaje al corazón de Europa para descubrir Suiza, este país alpino que nos espera con unos paisajes de ensueño, lagos alpinos, cautivadores pueblecitos tradicionales en contraste con las elegantes ciudades, todo esto hace de Suiza un destino único. Acompañados por guías en español visitaremos Zúrich, Berna, Ginebra o Lucerna, conoceremos el Castillo de Chillon, Grindelwald first o las Gargantas de Aareschlucht.",
      includ:"Traslado de llegada (aeropuerto – hotel) en Zurich/ Recorrido en autocar con guía de habla hispana / Visita panorámica en Ginebra / Subida en funicular a Grindelwald First / Entradas al Castillo de Chillon, fabrica de chocolate Cailler y Gargantas de Aareschlucht / Paseo en barco por el Lago Lemán / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / 2 comida indicada en el itinerario / Seguro turístico.",
      img:img3,
      category: "EUROPA",
    },
    {
      id: 10,
      name: "Maravillas de Tailandia 7 días desde Bangkok",
      stock: 20,
      price: 780,
      descrption:"Paquete al Sudeste Asiático para visitar Tailandia, el llamado país de las sonrisas. Acompañados por guías de habla hispana descubrirán los lugares imprescindibles de Tailandia. El paquete a Tailandia incluye la visita de Bangkok, una ciudad vibrante y llena de color, seguiremos dirección norte hasta el llamado Triángulo de Oro, punto de unión de 3 países fronterizos del río Mekong para conocer Chiang Mai y Chiang Rai, dos impresionantes ciudades norteñas de Tailandia.",
      includ:"Traslado de llegada en Bangkok (Aeropuerto – Hotel) y traslado de salida al aeropuerto de Chiang Mai / Recorrido en autocar con guía de habla hispana / Visita panorámica en Bangkok / Desayuno tipo buffet / Excursión Ofrenda a los monjes en Phitsanulok, al Triángulo de Oro en Chiang Rai, Safari a lomos de elefante y visita a una plantación de orquídeas en Chiang Mai / Entradas al Templo Wat Po y Templo Wat Traimit en Bangkok, Conjunto arqueológico en Ayutthaya, Templo de los Monos en Lopburi, Parque Arqueológico en Sukhotai, Museo del Opio y Templo Wat Rong Kun en Chiang Rai, Safari en elefante y Templo Doi Suthep en Chiang Mai / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / 4 Comidas o cenas indicadas en el itinerario / Seguro turístico.",
      img:img3,
      category: "ASIA",
    },
    {
      id: 11,
      name: "Triángulo dorado de India 7 días desde Delhi",
      stock: 20,
      price: 645,
      descrption:"Viaje a Asia del Sur para visitar las ciudades más turísticas de La India, segundo país más poblado del mundo y cuna de cuatro de las religiones más importantes del mundo, el hinduismo, el budismo, el jainismo y el sijismo. Este paquete les mostrará el Triángulo dorado de la India, formado por las ciudades de Nueva Delhi, una de las ciudades más bulliciosas del país, la ciudad rosada de Jaipur y Agra, hogar del mausoleo más popular del mundo e icono de la India, el Taj Majal.",
      includ:"Traslado de llegada y salida en Nueva Delhi / Recorrido en autocar con guía de habla hispana / Visitas panorámicas en Delhi, Jaipur y Agra / Excursiones: Paseo en Rickshaw en Delhi, Subida en elefante o en jeep al Fuerte Amber en Jaipur / Traslado nocturno a la Ceremonia Aarti en el Templo de Birla en Jaipur / Entradas a Raj Ghat, Mezquita Jama Masjid, Templo Comunidad Sij y Qutub Minar en Delhi, Fuerte Amber, Observatorio astronómico y al Palacio de la ciudad en Jaipur, Templo Baorí en Abhaneri, Recinto arqueológico en Fahtehpur Sikri, Taj Mahal y Fuerte Rojo en Agra / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / 10 Comidas o cenas indicadas en el itinerario / Seguro turístico.",
      img:img1,
      category: "ASIA",
    },
    {
      id: 12,
      name: "China de norte a sur 17 días desde Pekin",
      stock: 20,
      price: 3395,
      descrption:"Gran tour a través del milenario país del Oriente Lejano. Acompañados por expertos guías de habla hispana cruzamos China de norte a sur, desde Beijing hasta Hong Kong. Incluye la visita de Pekín y sus atractivos turísticos, la Gran Muralla China, también Shanghái y Xi’an, donde se encuentran los populares guerreros de terracota. Continuamos hacia el sur para llegar a Guilin donde embarcamos en un crucero por el Rio Li. El viaje a China finaliza en la vanguardista Hong Kong, una de las ciudades más modernas de Asia.",
      includ:"Traslado de llegada en Pekín (Aeropuerto – Hotel) / Recorrido en autocar con guía de habla hispana / Tickets de tren de alta velocidad entre Pekín – Shanghái, Shanghái – Louyang y Chengdu – Congjiang / Visitas panorámicas en Pekín, Shanghái, Xi’an, Cantón, Macao y Hong Kong / Excursión a la Gran Muralla desde Pekín, provincia de Sichuan desde Chengdu, Gruta de las Flautas de Caña en Guilin / Paseo en barco en Longmen, por el Lago de Quingcheng Shan en Chengdu, crucero por el río Li / Paseo en triciclo por los barrios tradicionales de Pekín / Traslado nocturno a Wangfujing en Pekín, a la Ciudad Vieja en Luoyang y en Hong Kong / Entradas a la Ciudad Prohibida, Parque Jingshan y Palacio de Verano en Pekín, Gran Muralla China, Jardín Yuyuan, demostración ceremonia del Té en Shanghai, Monasterio budista del Caballo Blanco en Luoyang, Cuevas Budistas en Longmen, Templo Baoulon, Museo Guo en Sanmexia, Museo del Ejército de Terracota, pequeña pagoda de la Oca Salvaje, demostración de caligrafía china, mezquita y espectáculo de tambores tradicionales en Torre del Tambor (cuando sea posible) en Xian, Sistema de irrigación de Dujiangyan, Montaña Sagrada de Quingcheng Shan en Chengdu, Pueblo Basha Miao, Visita Zhaoxing – etnia Dong, Visita pueblo Guangxiao – etnia Dong, Puente del viento en Chengyang, Terrazas de arroz en Longsheng, Gruta Flautas de Caña, Ciudad antigua en Huangyao, Casa del Clan Chen en Canton, Museo de Historia en Hong Kong / Funicular a la Gran Muralla, a la Montaña de Quingcheng Shan en Chengdu y el Peak Tram en Hong Kong / Ferry en Shanghái y Bahía de Hong Kong / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / 14 Comidas o cenas indicadas en el itinerario / Seguro turístico.",
      img:img2,
      category: "ASIA",
    },
    {
      id: 13,
      name: "Viaje a lo mejor de Corea & Japón 13 días",
      stock: 20,
      price: 3200,
      descrption:"Viaje combinado a Corea del Sur y Japón con guías de habla hispana para visitar lo mejor de Corea y Japón. El viaje incluye visita de Seúl, capital de Corea una mezcla de tradición y modernismo, Suwon con un centro histórico plagado de fortificaciones, los hanoks típicos coreanos (casas tradicionales de madera) en la aldea tradicional de Jeonju y también Busan, la segunda ciudad de Corea del Sur. Continuamos a Japón para conocer Hiroshima, la Isla de Itsukushima, el Tori de Miyajima, Osaka, el Monte Koya, Nagano y la capital de Japón, Tokio.",
      includ:"Traslado de llegada en Seúl (Aeropuerto – Hotel) / Recorrido en autocar con guía de habla hispana / Visitas panóramicas en Seúl, Kioto y Tokio / Desayuno tipo buffet / Traslado Nocturno a los barrios de Myeongdong en Seúl, Shinjuku en Tokio, Gion en Kioto / Tickets metro en Seúl y Tokio / Tickets de ferry entre Busan – Shimonoseki (nocturno), Hiroshima – Miyajima y Hiroshima – Matsuyama / Tickets tren de alta velocidad entre Kioto y Tokio / Entradas a Changdeokgung Palace, Gyeongbokgung Palace, Museo Memorial de la Guerra en Seúl, Hwaseong Haenggung, Samsung Innovation Museum en Suwon, Hanok Village en Jeonju, Templo Budista en Haeinsa, Templo Haedong Yonggung, Yongdusan Park, Cementerio Memorial de las Naciones Unidas y Doosan Haeundae en Busan, Kintaikyo en Iwakuni, Templo Itsukushima, Museo Memorial de la Paz en Hiroshima, Dogo Onsen, Templo Ishiteji en Matsuyama, Santuario de Kotohira, Jardines Ritsurin, Puente de Naruto, Museo Memorial del Terremoto en Kobe, Mausoleo de Okuno, Templo de Kongobuji en Monte Koya, Santuario Fushimi Inari, Palacio Imperial, Templo de Kinkaku-ji en Kioto, Templo Zojoji, Templo Meiji, Templo Sensoji en Tokio / Funicular al Castillo de Matsuyama / Sesión de meditación en Monte Koya / Alojamiento en hoteles de clase turista – superior / Desayuno buffet diario / 11 Comidas o cenas indicadas en el itinerario / Seguro turístico.",
      img:img3,
      category: "ASIA",
    },
]

export default data;